name: Test

on:
  push:

jobs:
  # Download from GitHub Releases
  precopmiled:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "25.1"
          elixir-version: "1.14.0"
      - run: mix deps.get
        working-directory: github_test
      - run: mix test
        working-directory: github_test
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Build from local
  force-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "25.1"
          elixir-version: "1.14.0"
      - run: mix deps.get
        working-directory: github_test
      - run: mix test
        working-directory: github_test
        env:
          RUSTLER_FORCE_BUILD: true
